var namespace_system_1_1_runtime_1_1_compiler_services_1_1_fakes =
[
    [ "StubCallConvCdecl", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_cdecl.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_cdecl" ],
    [ "StubCallConvFastcall", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_fastcall.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_fastcall" ],
    [ "StubCallConvStdcall", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_stdcall.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_stdcall" ],
    [ "StubCallConvThiscall", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_thiscall.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_call_conv_thiscall" ],
    [ "StubCompilationRelaxationsAttribute", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_compilation_relaxations_attribute.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_compilation_relaxations_attribute" ],
    [ "StubCompilerGlobalScopeAttribute", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_compiler_global_scope_attribute.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_compiler_global_scope_attribute" ],
    [ "StubCustomConstantAttribute", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_custom_constant_attribute.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_custom_constant_attribute" ],
    [ "StubDiscardableAttribute", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_discardable_attribute.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_discardable_attribute" ],
    [ "StubIAsyncStateMachine", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_async_state_machine.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_async_state_machine" ],
    [ "StubICriticalNotifyCompletion", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_critical_notify_completion.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_critical_notify_completion" ],
    [ "StubINotifyCompletion", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_notify_completion.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_i_notify_completion" ],
    [ "StubStateMachineAttribute", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_state_machine_attribute.html", "class_system_1_1_runtime_1_1_compiler_services_1_1_fakes_1_1_stub_state_machine_attribute" ]
];