var namespace_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes =
[
    [ "StubDesignerNamespaceResolveEventArgs", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_designer_namespace_resolve_event_args.html", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_designer_namespace_resolve_event_args" ],
    [ "StubIActivationFactory", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_i_activation_factory.html", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_i_activation_factory" ],
    [ "StubNamespaceResolveEventArgs", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_namespace_resolve_event_args.html", "class_system_1_1_runtime_1_1_interop_services_1_1_windows_runtime_1_1_fakes_1_1_stub_namespace_resolve_event_args" ]
];