var namespace_system_1_1_net_1_1_fakes =
[
    [ "StubAuthorization", "class_system_1_1_net_1_1_fakes_1_1_stub_authorization.html", "class_system_1_1_net_1_1_fakes_1_1_stub_authorization" ],
    [ "StubCookieCollection", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_collection.html", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_collection" ],
    [ "StubCookieContainer", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_container.html", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_container" ],
    [ "StubCookieException", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_exception.html", "class_system_1_1_net_1_1_fakes_1_1_stub_cookie_exception" ],
    [ "StubCredentialCache", "class_system_1_1_net_1_1_fakes_1_1_stub_credential_cache.html", "class_system_1_1_net_1_1_fakes_1_1_stub_credential_cache" ],
    [ "StubDnsEndPoint", "class_system_1_1_net_1_1_fakes_1_1_stub_dns_end_point.html", "class_system_1_1_net_1_1_fakes_1_1_stub_dns_end_point" ],
    [ "StubEndPoint", "class_system_1_1_net_1_1_fakes_1_1_stub_end_point.html", "class_system_1_1_net_1_1_fakes_1_1_stub_end_point" ],
    [ "StubFileWebRequest", "class_system_1_1_net_1_1_fakes_1_1_stub_file_web_request.html", "class_system_1_1_net_1_1_fakes_1_1_stub_file_web_request" ],
    [ "StubFileWebResponse", "class_system_1_1_net_1_1_fakes_1_1_stub_file_web_response.html", "class_system_1_1_net_1_1_fakes_1_1_stub_file_web_response" ],
    [ "StubHttpListenerException", "class_system_1_1_net_1_1_fakes_1_1_stub_http_listener_exception.html", "class_system_1_1_net_1_1_fakes_1_1_stub_http_listener_exception" ],
    [ "StubHttpVersion", "class_system_1_1_net_1_1_fakes_1_1_stub_http_version.html", "class_system_1_1_net_1_1_fakes_1_1_stub_http_version" ],
    [ "StubIAuthenticationModule", "class_system_1_1_net_1_1_fakes_1_1_stub_i_authentication_module.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_authentication_module" ],
    [ "StubICertificatePolicy", "class_system_1_1_net_1_1_fakes_1_1_stub_i_certificate_policy.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_certificate_policy" ],
    [ "StubICredentialPolicy", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credential_policy.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credential_policy" ],
    [ "StubICredentials", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credentials.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credentials" ],
    [ "StubICredentialsByHost", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credentials_by_host.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_credentials_by_host" ],
    [ "StubIPAddress", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_address.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_address" ],
    [ "StubIPEndPoint", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_end_point.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_end_point" ],
    [ "StubIPHostEntry", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_host_entry.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_p_host_entry" ],
    [ "StubIWebProxy", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_proxy.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_proxy" ],
    [ "StubIWebProxyScript", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_proxy_script.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_proxy_script" ],
    [ "StubIWebRequestCreate", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_request_create.html", "class_system_1_1_net_1_1_fakes_1_1_stub_i_web_request_create" ],
    [ "StubNetworkCredential", "class_system_1_1_net_1_1_fakes_1_1_stub_network_credential.html", "class_system_1_1_net_1_1_fakes_1_1_stub_network_credential" ],
    [ "StubProtocolViolationException", "class_system_1_1_net_1_1_fakes_1_1_stub_protocol_violation_exception.html", "class_system_1_1_net_1_1_fakes_1_1_stub_protocol_violation_exception" ],
    [ "StubSocketAddress", "class_system_1_1_net_1_1_fakes_1_1_stub_socket_address.html", "class_system_1_1_net_1_1_fakes_1_1_stub_socket_address" ],
    [ "StubTransportContext", "class_system_1_1_net_1_1_fakes_1_1_stub_transport_context.html", "class_system_1_1_net_1_1_fakes_1_1_stub_transport_context" ],
    [ "StubWebException", "class_system_1_1_net_1_1_fakes_1_1_stub_web_exception.html", "class_system_1_1_net_1_1_fakes_1_1_stub_web_exception" ],
    [ "StubWebHeaderCollection", "class_system_1_1_net_1_1_fakes_1_1_stub_web_header_collection.html", "class_system_1_1_net_1_1_fakes_1_1_stub_web_header_collection" ],
    [ "StubWebProxy", "class_system_1_1_net_1_1_fakes_1_1_stub_web_proxy.html", "class_system_1_1_net_1_1_fakes_1_1_stub_web_proxy" ],
    [ "StubWebResponse", "class_system_1_1_net_1_1_fakes_1_1_stub_web_response.html", "class_system_1_1_net_1_1_fakes_1_1_stub_web_response" ]
];