var namespace_system_1_1_fakes =
[
    [ "ShimDateTime", "class_system_1_1_fakes_1_1_shim_date_time.html", null ],
    [ "ShimGuid", "class_system_1_1_fakes_1_1_shim_guid.html", null ],
    [ "StubAccessViolationException", "class_system_1_1_fakes_1_1_stub_access_violation_exception.html", "class_system_1_1_fakes_1_1_stub_access_violation_exception" ],
    [ "StubAggregateException", "class_system_1_1_fakes_1_1_stub_aggregate_exception.html", "class_system_1_1_fakes_1_1_stub_aggregate_exception" ],
    [ "StubAppDomainManager", "class_system_1_1_fakes_1_1_stub_app_domain_manager.html", "class_system_1_1_fakes_1_1_stub_app_domain_manager" ],
    [ "StubAppDomainUnloadedException", "class_system_1_1_fakes_1_1_stub_app_domain_unloaded_exception.html", "class_system_1_1_fakes_1_1_stub_app_domain_unloaded_exception" ],
    [ "StubApplicationException", "class_system_1_1_fakes_1_1_stub_application_exception.html", "class_system_1_1_fakes_1_1_stub_application_exception" ],
    [ "StubArgumentException", "class_system_1_1_fakes_1_1_stub_argument_exception.html", "class_system_1_1_fakes_1_1_stub_argument_exception" ],
    [ "StubArgumentNullException", "class_system_1_1_fakes_1_1_stub_argument_null_exception.html", "class_system_1_1_fakes_1_1_stub_argument_null_exception" ],
    [ "StubArgumentOutOfRangeException", "class_system_1_1_fakes_1_1_stub_argument_out_of_range_exception.html", "class_system_1_1_fakes_1_1_stub_argument_out_of_range_exception" ],
    [ "StubArithmeticException", "class_system_1_1_fakes_1_1_stub_arithmetic_exception.html", "class_system_1_1_fakes_1_1_stub_arithmetic_exception" ],
    [ "StubArrayTypeMismatchException", "class_system_1_1_fakes_1_1_stub_array_type_mismatch_exception.html", "class_system_1_1_fakes_1_1_stub_array_type_mismatch_exception" ],
    [ "StubAssemblyLoadEventArgs", "class_system_1_1_fakes_1_1_stub_assembly_load_event_args.html", "class_system_1_1_fakes_1_1_stub_assembly_load_event_args" ],
    [ "StubAttribute", "class_system_1_1_fakes_1_1_stub_attribute.html", "class_system_1_1_fakes_1_1_stub_attribute" ],
    [ "StubBadImageFormatException", "class_system_1_1_fakes_1_1_stub_bad_image_format_exception.html", "class_system_1_1_fakes_1_1_stub_bad_image_format_exception" ],
    [ "StubCannotUnloadAppDomainException", "class_system_1_1_fakes_1_1_stub_cannot_unload_app_domain_exception.html", "class_system_1_1_fakes_1_1_stub_cannot_unload_app_domain_exception" ],
    [ "StubContextBoundObject", "class_system_1_1_fakes_1_1_stub_context_bound_object.html", "class_system_1_1_fakes_1_1_stub_context_bound_object" ],
    [ "StubContextMarshalException", "class_system_1_1_fakes_1_1_stub_context_marshal_exception.html", "class_system_1_1_fakes_1_1_stub_context_marshal_exception" ],
    [ "StubContextStaticAttribute", "class_system_1_1_fakes_1_1_stub_context_static_attribute.html", "class_system_1_1_fakes_1_1_stub_context_static_attribute" ],
    [ "StubDivideByZeroException", "class_system_1_1_fakes_1_1_stub_divide_by_zero_exception.html", "class_system_1_1_fakes_1_1_stub_divide_by_zero_exception" ],
    [ "StubDllNotFoundException", "class_system_1_1_fakes_1_1_stub_dll_not_found_exception.html", "class_system_1_1_fakes_1_1_stub_dll_not_found_exception" ],
    [ "StubDuplicateWaitObjectException", "class_system_1_1_fakes_1_1_stub_duplicate_wait_object_exception.html", "class_system_1_1_fakes_1_1_stub_duplicate_wait_object_exception" ],
    [ "StubEntryPointNotFoundException", "class_system_1_1_fakes_1_1_stub_entry_point_not_found_exception.html", "class_system_1_1_fakes_1_1_stub_entry_point_not_found_exception" ],
    [ "StubEventArgs", "class_system_1_1_fakes_1_1_stub_event_args.html", "class_system_1_1_fakes_1_1_stub_event_args" ],
    [ "StubException", "class_system_1_1_fakes_1_1_stub_exception.html", "class_system_1_1_fakes_1_1_stub_exception" ],
    [ "StubFieldAccessException", "class_system_1_1_fakes_1_1_stub_field_access_exception.html", "class_system_1_1_fakes_1_1_stub_field_access_exception" ],
    [ "StubFlagsAttribute", "class_system_1_1_fakes_1_1_stub_flags_attribute.html", "class_system_1_1_fakes_1_1_stub_flags_attribute" ],
    [ "StubFormatException", "class_system_1_1_fakes_1_1_stub_format_exception.html", "class_system_1_1_fakes_1_1_stub_format_exception" ],
    [ "StubIAppDomainSetup", "class_system_1_1_fakes_1_1_stub_i_app_domain_setup.html", "class_system_1_1_fakes_1_1_stub_i_app_domain_setup" ],
    [ "StubIAsyncResult", "class_system_1_1_fakes_1_1_stub_i_async_result.html", "class_system_1_1_fakes_1_1_stub_i_async_result" ],
    [ "StubICloneable", "class_system_1_1_fakes_1_1_stub_i_cloneable.html", "class_system_1_1_fakes_1_1_stub_i_cloneable" ],
    [ "StubIComparable", "class_system_1_1_fakes_1_1_stub_i_comparable.html", "class_system_1_1_fakes_1_1_stub_i_comparable" ],
    [ "StubIComparable< T >", "class_system_1_1_fakes_1_1_stub_i_comparable_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_i_comparable_3_01_t_01_4" ],
    [ "StubIConvertible", "class_system_1_1_fakes_1_1_stub_i_convertible.html", "class_system_1_1_fakes_1_1_stub_i_convertible" ],
    [ "StubICustomFormatter", "class_system_1_1_fakes_1_1_stub_i_custom_formatter.html", "class_system_1_1_fakes_1_1_stub_i_custom_formatter" ],
    [ "StubIDisposable", "class_system_1_1_fakes_1_1_stub_i_disposable.html", "class_system_1_1_fakes_1_1_stub_i_disposable" ],
    [ "StubIEquatable< T >", "class_system_1_1_fakes_1_1_stub_i_equatable_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_i_equatable_3_01_t_01_4" ],
    [ "StubIFormatProvider", "class_system_1_1_fakes_1_1_stub_i_format_provider.html", "class_system_1_1_fakes_1_1_stub_i_format_provider" ],
    [ "StubIFormattable", "class_system_1_1_fakes_1_1_stub_i_formattable.html", "class_system_1_1_fakes_1_1_stub_i_formattable" ],
    [ "StubIObservable< T >", "class_system_1_1_fakes_1_1_stub_i_observable_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_i_observable_3_01_t_01_4" ],
    [ "StubIObserver< T >", "class_system_1_1_fakes_1_1_stub_i_observer_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_i_observer_3_01_t_01_4" ],
    [ "StubIProgress< T >", "class_system_1_1_fakes_1_1_stub_i_progress_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_i_progress_3_01_t_01_4" ],
    [ "StubIServiceProvider", "class_system_1_1_fakes_1_1_stub_i_service_provider.html", "class_system_1_1_fakes_1_1_stub_i_service_provider" ],
    [ "StubInvalidCastException", "class_system_1_1_fakes_1_1_stub_invalid_cast_exception.html", "class_system_1_1_fakes_1_1_stub_invalid_cast_exception" ],
    [ "StubInvalidOperationException", "class_system_1_1_fakes_1_1_stub_invalid_operation_exception.html", "class_system_1_1_fakes_1_1_stub_invalid_operation_exception" ],
    [ "StubInvalidTimeZoneException", "class_system_1_1_fakes_1_1_stub_invalid_time_zone_exception.html", "class_system_1_1_fakes_1_1_stub_invalid_time_zone_exception" ],
    [ "StubLazy< T >", "class_system_1_1_fakes_1_1_stub_lazy_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_lazy_3_01_t_01_4" ],
    [ "StubMarshalByRefObject", "class_system_1_1_fakes_1_1_stub_marshal_by_ref_object.html", "class_system_1_1_fakes_1_1_stub_marshal_by_ref_object" ],
    [ "StubMemberAccessException", "class_system_1_1_fakes_1_1_stub_member_access_exception.html", "class_system_1_1_fakes_1_1_stub_member_access_exception" ],
    [ "StubMethodAccessException", "class_system_1_1_fakes_1_1_stub_method_access_exception.html", "class_system_1_1_fakes_1_1_stub_method_access_exception" ],
    [ "StubMissingFieldException", "class_system_1_1_fakes_1_1_stub_missing_field_exception.html", "class_system_1_1_fakes_1_1_stub_missing_field_exception" ],
    [ "StubMissingMemberException", "class_system_1_1_fakes_1_1_stub_missing_member_exception.html", "class_system_1_1_fakes_1_1_stub_missing_member_exception" ],
    [ "StubMissingMethodException", "class_system_1_1_fakes_1_1_stub_missing_method_exception.html", "class_system_1_1_fakes_1_1_stub_missing_method_exception" ],
    [ "StubNotFiniteNumberException", "class_system_1_1_fakes_1_1_stub_not_finite_number_exception.html", "class_system_1_1_fakes_1_1_stub_not_finite_number_exception" ],
    [ "StubNotImplementedException", "class_system_1_1_fakes_1_1_stub_not_implemented_exception.html", "class_system_1_1_fakes_1_1_stub_not_implemented_exception" ],
    [ "StubNotSupportedException", "class_system_1_1_fakes_1_1_stub_not_supported_exception.html", "class_system_1_1_fakes_1_1_stub_not_supported_exception" ],
    [ "StubNullReferenceException", "class_system_1_1_fakes_1_1_stub_null_reference_exception.html", "class_system_1_1_fakes_1_1_stub_null_reference_exception" ],
    [ "StubObject", "class_system_1_1_fakes_1_1_stub_object.html", "class_system_1_1_fakes_1_1_stub_object" ],
    [ "StubObjectDisposedException", "class_system_1_1_fakes_1_1_stub_object_disposed_exception.html", "class_system_1_1_fakes_1_1_stub_object_disposed_exception" ],
    [ "StubOperationCanceledException", "class_system_1_1_fakes_1_1_stub_operation_canceled_exception.html", "class_system_1_1_fakes_1_1_stub_operation_canceled_exception" ],
    [ "StubOutOfMemoryException", "class_system_1_1_fakes_1_1_stub_out_of_memory_exception.html", "class_system_1_1_fakes_1_1_stub_out_of_memory_exception" ],
    [ "StubOverflowException", "class_system_1_1_fakes_1_1_stub_overflow_exception.html", "class_system_1_1_fakes_1_1_stub_overflow_exception" ],
    [ "StubPlatformNotSupportedException", "class_system_1_1_fakes_1_1_stub_platform_not_supported_exception.html", "class_system_1_1_fakes_1_1_stub_platform_not_supported_exception" ],
    [ "StubProgress< T >", "class_system_1_1_fakes_1_1_stub_progress_3_01_t_01_4.html", "class_system_1_1_fakes_1_1_stub_progress_3_01_t_01_4" ],
    [ "StubRandom", "class_system_1_1_fakes_1_1_stub_random.html", "class_system_1_1_fakes_1_1_stub_random" ],
    [ "StubRankException", "class_system_1_1_fakes_1_1_stub_rank_exception.html", "class_system_1_1_fakes_1_1_stub_rank_exception" ],
    [ "StubResolveEventArgs", "class_system_1_1_fakes_1_1_stub_resolve_event_args.html", "class_system_1_1_fakes_1_1_stub_resolve_event_args" ],
    [ "StubStringComparer", "class_system_1_1_fakes_1_1_stub_string_comparer.html", "class_system_1_1_fakes_1_1_stub_string_comparer" ],
    [ "StubSystemException", "class_system_1_1_fakes_1_1_stub_system_exception.html", "class_system_1_1_fakes_1_1_stub_system_exception" ],
    [ "StubThreadStaticAttribute", "class_system_1_1_fakes_1_1_stub_thread_static_attribute.html", "class_system_1_1_fakes_1_1_stub_thread_static_attribute" ],
    [ "StubTimeZone", "class_system_1_1_fakes_1_1_stub_time_zone.html", "class_system_1_1_fakes_1_1_stub_time_zone" ],
    [ "StubTimeZoneNotFoundException", "class_system_1_1_fakes_1_1_stub_time_zone_not_found_exception.html", "class_system_1_1_fakes_1_1_stub_time_zone_not_found_exception" ],
    [ "StubTimeoutException", "class_system_1_1_fakes_1_1_stub_timeout_exception.html", "class_system_1_1_fakes_1_1_stub_timeout_exception" ],
    [ "StubTuple< T1 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_01_4" ],
    [ "StubTuple< T1, T2 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_01_4" ],
    [ "StubTuple< T1, T2, T3 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_01_4" ],
    [ "StubTuple< T1, T2, T3, T4 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_01_4" ],
    [ "StubTuple< T1, T2, T3, T4, T5 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_01_4" ],
    [ "StubTuple< T1, T2, T3, T4, T5, T6 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_01_4" ],
    [ "StubTuple< T1, T2, T3, T4, T5, T6, T7 >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_00_01_t7_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_00_01_t7_01_4" ],
    [ "StubTuple< T1, T2, T3, T4, T5, T6, T7, TRest >", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_00_01_t7_00_01_t_rest_01_4.html", "class_system_1_1_fakes_1_1_stub_tuple_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_00_01_t7_00_01_t_rest_01_4" ],
    [ "StubType", "class_system_1_1_fakes_1_1_stub_type.html", "class_system_1_1_fakes_1_1_stub_type" ],
    [ "StubTypeAccessException", "class_system_1_1_fakes_1_1_stub_type_access_exception.html", "class_system_1_1_fakes_1_1_stub_type_access_exception" ],
    [ "StubTypeLoadException", "class_system_1_1_fakes_1_1_stub_type_load_exception.html", "class_system_1_1_fakes_1_1_stub_type_load_exception" ],
    [ "StubTypeUnloadedException", "class_system_1_1_fakes_1_1_stub_type_unloaded_exception.html", "class_system_1_1_fakes_1_1_stub_type_unloaded_exception" ],
    [ "StubUnauthorizedAccessException", "class_system_1_1_fakes_1_1_stub_unauthorized_access_exception.html", "class_system_1_1_fakes_1_1_stub_unauthorized_access_exception" ],
    [ "StubUnhandledExceptionEventArgs", "class_system_1_1_fakes_1_1_stub_unhandled_exception_event_args.html", "class_system_1_1_fakes_1_1_stub_unhandled_exception_event_args" ],
    [ "StubWeakReference", "class_system_1_1_fakes_1_1_stub_weak_reference.html", "class_system_1_1_fakes_1_1_stub_weak_reference" ],
    [ "Stub_AppDomain", "class_system_1_1_fakes_1_1_stub___app_domain.html", "class_system_1_1_fakes_1_1_stub___app_domain" ],
    [ "StubFileStyleUriParser", "class_system_1_1_fakes_1_1_stub_file_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_file_style_uri_parser" ],
    [ "StubFtpStyleUriParser", "class_system_1_1_fakes_1_1_stub_ftp_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_ftp_style_uri_parser" ],
    [ "StubGenericUriParser", "class_system_1_1_fakes_1_1_stub_generic_uri_parser.html", "class_system_1_1_fakes_1_1_stub_generic_uri_parser" ],
    [ "StubGopherStyleUriParser", "class_system_1_1_fakes_1_1_stub_gopher_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_gopher_style_uri_parser" ],
    [ "StubHttpStyleUriParser", "class_system_1_1_fakes_1_1_stub_http_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_http_style_uri_parser" ],
    [ "StubLdapStyleUriParser", "class_system_1_1_fakes_1_1_stub_ldap_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_ldap_style_uri_parser" ],
    [ "StubNetPipeStyleUriParser", "class_system_1_1_fakes_1_1_stub_net_pipe_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_net_pipe_style_uri_parser" ],
    [ "StubNetTcpStyleUriParser", "class_system_1_1_fakes_1_1_stub_net_tcp_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_net_tcp_style_uri_parser" ],
    [ "StubNewsStyleUriParser", "class_system_1_1_fakes_1_1_stub_news_style_uri_parser.html", "class_system_1_1_fakes_1_1_stub_news_style_uri_parser" ],
    [ "StubUri", "class_system_1_1_fakes_1_1_stub_uri.html", "class_system_1_1_fakes_1_1_stub_uri" ],
    [ "StubUriBuilder", "class_system_1_1_fakes_1_1_stub_uri_builder.html", "class_system_1_1_fakes_1_1_stub_uri_builder" ],
    [ "StubUriFormatException", "class_system_1_1_fakes_1_1_stub_uri_format_exception.html", "class_system_1_1_fakes_1_1_stub_uri_format_exception" ],
    [ "StubUriParser", "class_system_1_1_fakes_1_1_stub_uri_parser.html", "class_system_1_1_fakes_1_1_stub_uri_parser" ],
    [ "StubUriTypeConverter", "class_system_1_1_fakes_1_1_stub_uri_type_converter.html", "class_system_1_1_fakes_1_1_stub_uri_type_converter" ]
];