var namespace_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes =
[
    [ "StubCriticalHandleMinusOneIsInvalid", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_critical_handle_minus_one_is_invalid.html", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_critical_handle_minus_one_is_invalid" ],
    [ "StubCriticalHandleZeroOrMinusOneIsInvalid", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_critical_handle_zero_or_minus_one_is_invalid.html", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_critical_handle_zero_or_minus_one_is_invalid" ],
    [ "StubSafeHandleMinusOneIsInvalid", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_safe_handle_minus_one_is_invalid.html", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_safe_handle_minus_one_is_invalid" ],
    [ "StubSafeHandleZeroOrMinusOneIsInvalid", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_safe_handle_zero_or_minus_one_is_invalid.html", "class_microsoft_1_1_win32_1_1_safe_handles_1_1_fakes_1_1_stub_safe_handle_zero_or_minus_one_is_invalid" ]
];