var namespace_system_1_1_runtime_1_1_exception_services_1_1_fakes =
[
    [ "StubFirstChanceExceptionEventArgs", "class_system_1_1_runtime_1_1_exception_services_1_1_fakes_1_1_stub_first_chance_exception_event_args.html", "class_system_1_1_runtime_1_1_exception_services_1_1_fakes_1_1_stub_first_chance_exception_event_args" ]
];