var namespace_system_1_1_i_o_1_1_isolated_storage_1_1_fakes =
[
    [ "StubINormalizeForIsolatedStorage", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_i_normalize_for_isolated_storage.html", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_i_normalize_for_isolated_storage" ],
    [ "StubIsolatedStorage", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage.html", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage" ],
    [ "StubIsolatedStorageException", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage_exception.html", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage_exception" ],
    [ "StubIsolatedStorageFileStream", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage_file_stream.html", "class_system_1_1_i_o_1_1_isolated_storage_1_1_fakes_1_1_stub_isolated_storage_file_stream" ]
];