var namespace_system_1_1_configuration_1_1_fakes =
[
    [ "ShimConfigurationSettings", "class_system_1_1_configuration_1_1_fakes_1_1_shim_configuration_settings.html", "class_system_1_1_configuration_1_1_fakes_1_1_shim_configuration_settings" ],
    [ "StubAppSettingsReader", "class_system_1_1_configuration_1_1_fakes_1_1_stub_app_settings_reader.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_app_settings_reader" ],
    [ "StubApplicationSettingsBase", "class_system_1_1_configuration_1_1_fakes_1_1_stub_application_settings_base.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_application_settings_base" ],
    [ "StubConfigurationException", "class_system_1_1_configuration_1_1_fakes_1_1_stub_configuration_exception.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_configuration_exception" ],
    [ "StubDictionarySectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_dictionary_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_dictionary_section_handler" ],
    [ "StubIApplicationSettingsProvider", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_application_settings_provider.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_application_settings_provider" ],
    [ "StubIConfigurationSectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_configuration_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_configuration_section_handler" ],
    [ "StubIConfigurationSystem", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_configuration_system.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_configuration_system" ],
    [ "StubIPersistComponentSettings", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_persist_component_settings.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_persist_component_settings" ],
    [ "StubISettingsProviderService", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_settings_provider_service.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_i_settings_provider_service" ],
    [ "StubIgnoreSectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_ignore_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_ignore_section_handler" ],
    [ "StubLocalFileSettingsProvider", "class_system_1_1_configuration_1_1_fakes_1_1_stub_local_file_settings_provider.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_local_file_settings_provider" ],
    [ "StubNameValueFileSectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_name_value_file_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_name_value_file_section_handler" ],
    [ "StubNameValueSectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_name_value_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_name_value_section_handler" ],
    [ "StubSettingAttribute", "class_system_1_1_configuration_1_1_fakes_1_1_stub_setting_attribute.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_setting_attribute" ],
    [ "StubSettingChangingEventArgs", "class_system_1_1_configuration_1_1_fakes_1_1_stub_setting_changing_event_args.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_setting_changing_event_args" ],
    [ "StubSettingsAttributeDictionary", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_attribute_dictionary.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_attribute_dictionary" ],
    [ "StubSettingsBase", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_base.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_base" ],
    [ "StubSettingsContext", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_context.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_context" ],
    [ "StubSettingsLoadedEventArgs", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_loaded_event_args.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_loaded_event_args" ],
    [ "StubSettingsProperty", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property" ],
    [ "StubSettingsPropertyCollection", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_collection.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_collection" ],
    [ "StubSettingsPropertyIsReadOnlyException", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_is_read_only_exception.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_is_read_only_exception" ],
    [ "StubSettingsPropertyNotFoundException", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_not_found_exception.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_not_found_exception" ],
    [ "StubSettingsPropertyValue", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_value.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_value" ],
    [ "StubSettingsPropertyValueCollection", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_value_collection.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_value_collection" ],
    [ "StubSettingsPropertyWrongTypeException", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_wrong_type_exception.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_property_wrong_type_exception" ],
    [ "StubSettingsProvider", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_provider.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_provider" ],
    [ "StubSettingsProviderCollection", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_provider_collection.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_settings_provider_collection" ],
    [ "StubSingleTagSectionHandler", "class_system_1_1_configuration_1_1_fakes_1_1_stub_single_tag_section_handler.html", "class_system_1_1_configuration_1_1_fakes_1_1_stub_single_tag_section_handler" ]
];