//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerEUCases.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long DocumentId { get; set; }
        public string DocumentFormat { get; set; }
        public string DocumentName { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> Operation { get; set; }
        public string Url { get; set; }
        public string Md5 { get; set; }
        public long DocumentGroupId { get; set; }
    
        public virtual DocumentGroup DocumentGroup { get; set; }
    }
}
