//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerEUCases.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentGroup
    {
        public DocumentGroup()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public long DocumentGroupId { get; set; }
        public string DocumentGroupDate { get; set; }
        public string DocumentGroupName { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> Operation { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
    }
}
