//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler.ServiceEUCasesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadDocumentGroup", Namespace="http://schemas.datacontract.org/2004/07/ServiceEUCases")]
    [System.SerializableAttribute()]
    public partial class UploadDocumentGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetaInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaInfo {
            get {
                return this.MetaInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaInfoField, value) != true)) {
                    this.MetaInfoField = value;
                    this.RaisePropertyChanged("MetaInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEUCasesReference.IServiceEUCases")]
    public interface IServiceEUCases {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEUCases/UploadFile", ReplyAction="http://tempuri.org/IServiceEUCases/UploadFileResponse")]
        string UploadFile(Crawler.ServiceEUCasesReference.UploadDocumentGroup document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEUCases/UploadFile", ReplyAction="http://tempuri.org/IServiceEUCases/UploadFileResponse")]
        System.Threading.Tasks.Task<string> UploadFileAsync(Crawler.ServiceEUCasesReference.UploadDocumentGroup document);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEUCasesChannel : Crawler.ServiceEUCasesReference.IServiceEUCases, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEUCasesClient : System.ServiceModel.ClientBase<Crawler.ServiceEUCasesReference.IServiceEUCases>, Crawler.ServiceEUCasesReference.IServiceEUCases {
        
        public ServiceEUCasesClient() {
        }
        
        public ServiceEUCasesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEUCasesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEUCasesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEUCasesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadFile(Crawler.ServiceEUCasesReference.UploadDocumentGroup document) {
            return base.Channel.UploadFile(document);
        }
        
        public System.Threading.Tasks.Task<string> UploadFileAsync(Crawler.ServiceEUCasesReference.UploadDocumentGroup document) {
            return base.Channel.UploadFileAsync(document);
        }
    }
}
