//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEUCases.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlerLog
    {
        public int CrawlerLogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string IpAddress { get; set; }
        public string MetaXml { get; set; }
        public Nullable<int> ZipLength { get; set; }
        public Nullable<int> Operation { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Error { get; set; }
        public string CrawlerName { get; set; }
        public string Identifier { get; set; }
    }
}
